name: Make Docs
on:
  pull_request:
    branches: "master"
  push:
    branches:
      - master
    tags: '*'
  workflow_dispatch:
    
jobs:
  make_docs:
    uses: ProjectTorreyPines/GitHubActionsWorkflows/workflows/make_docs.yml@master
