name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - dev
  pull_request:

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - "1.x"
        os:
          - ubuntu-latest
        arch:
          - x64

    steps:
      - uses: actions/checkout@v4

      - uses: julia-actions/setup-julia@latest

      - uses: julia-actions/cache@v2

      - name: Add FuseRegistry
        run: |
          rm -rf ~/.julia/registries/FuseRegistry
          julia -e 'using Pkg; Pkg.Registry.add(RegistrySpec(url="https://github.com/ProjectTorreyPines/FuseRegistry.jl.git")); Pkg.Registry.add("General"); Pkg.Registry.update()'

      - name: Replace git@github.com with https in Package.toml files
        run: |
          find ~/.julia/registries/FuseRegistry -type f -name 'Package.toml' -exec sed -i 's|git@github.com:|https://project-torrey-pines:${{secrets.PTP_READ_TOKEN}}@github.com/|g' {} +

      - name: Install dependencies
        run: |
          julia -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()
          '

      - uses: julia-actions/julia-buildpkg@v1

      - uses: julia-actions/julia-runtest@v1
